name: My Github Actions Workflow # name of the workflow
on: [push] # event that triggers the GA workflow

# group of steps the execute on the run up
jobs: 
  testing_github:
    runs-on: ubuntu-latest     #execution environment for the job
    steps: 
      - name: Hello
        run: echo "Hello, Github Actions"
      - name: Display repo name # github context variable shows how we can use dynamic values in our workflow
        run: echo "this workflow is running in ${{ github.repository}}"